BistroManagementTool/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls import url
from BistroManagementToolApp import views
from django.urls import path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^bistro/',include("BistroManagementToolApp.urls")),
]

BistroManagementToolApp/urls.py
from django.urls import path
from django.conf.urls import url
from BistroManagementToolApp import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'BistroManagementToolApp'

urlpatterns = [

    url(r'^panel_logowania',views.panel_logowania,name='panel_logowania'),
    url(r'^login_required_page',views.login_required_page,name='login_required_page'),
    url(r'^brak_uprawnien',views.brak_uprawnien,name='brak_uprawnien'),
    url(r'^wrong_credentials_page',views.wrong_credentials_page,name='wrong_credentials_page'),
    url(r'^panel_zarzadzania_zespolem',views.panel_zarzadzania_zespolem,name='panel_zarzadzania_zespolem'),
    url(r'^panel_sprzedawcy',views.panel_sprzedawcy,name='panel_sprzedawcy'),
    url(r'^panel_administratora',views.panel_administratora,name='panel_administratora'),
    url(r'^panel_transakcji',views.panel_transakcji,name='panel_transakcji'),
    url(r'^panel_magazynu',views.panel_magazynu,name='panel_magazynu'),
    url(r'^ajax/change_ing_category',views.change_ing_category,name='change_ing_category'),
    url(r'^ajax/change_ing_subcategory',views.change_ing_subcategory,name='change_ing_subcategory'),
    url(r'^ajax/delete_ingredient',views.delete_ingredient,name="delete_ingredient"),
    url(r'^ajax/create_ingredient',views.create_ingredient,name="create_ingredient"),
    url(r'^ajax/update_ingredient',views.update_ingredient,name="update_ingredient"),
    url(r'^ajax/create_user',views.create_user,name="create_user"),
    url(r'^ajax/delete_user',views.delete_user,name="delete_user"),
    url(r'^ajax/edit_user',views.edit_user,name="edit_user"),
    url(r'^logout_user',views.logout_user,name="logout_user"),
    url(r'^test',views.test_env,name="test_env")


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BistroManagementToolApp/forms.py
from django import forms
from django.contrib.auth.models import User
from BistroManagementToolApp.models import *

class TransactionForm(forms.ModelForm):
    class Meta():
        model = Transaction
        fields = '__all__'

class ProductsInTransactionForm(forms.ModelForm):
    class Meta():
        model = ProductsInTransaction
        fields = '__all__'

class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())


    class Meta():
        model = User
        fields = ('username','first_name','last_name','email','password')
        labels = {
            'username':'Nazwa użytkownika',
            'first_name':'Imię',
            'last_name':'Nazwisko',
            'email':'Adres email',
            'password':'Hasło'
        }

class ApplicationUserForm(forms.ModelForm):
    class Meta():
        model = ApplicationUser
        fields = ('picture',)

        labels = {
            'picture':'Zdjęcie pracownika',
            'salary':'Wynagrodzenie'
         }

class IngredientForm(forms.ModelForm):

    init_cat = IngredientCategory.objects.all()[:1].get()
    init_subcat = IngredientSubcategory.objects.all().filter(category=init_cat)[:1].get()

    category = forms.ModelChoiceField(initial=0,queryset=IngredientCategory.objects.all(),widget=forms.Select(attrs={'style': 'height:100%'}))
    subcategory = forms.ModelChoiceField(initial=0,queryset=IngredientSubcategory.objects.filter(category=init_cat),widget=forms.Select(attrs={'style': 'height:100%'}))
    aisle = forms.ModelChoiceField(initial=0,queryset=IngredientAisle.objects.filter(subcategory=init_subcat),widget=forms.Select(attrs={'style': 'height:100%'}))

    class Meta():
        model = Ingredient
        exclude = ['ext_id','date_created','status','netto_price_per_unit','netto_price_per_package','brutto_price_per_unit','amount_in_storage']

        UNITS = [("g", "g"), ("dag", "dag"), ("kg", "kg"), ("ml", "ml"), ("l", "l"), ("szt", "szt")]
        VAT_RATE = [('0.23', '23%'), ('0.08', '8%'), ('0.05', '5%')]

        widgets = {

            'unit':forms.Select(choices=UNITS, attrs={'style':'width:100%','style':'height:100%'}),
            'grammature_per_package':forms.NumberInput(attrs={'style':'width:100%'}),
            'vat_rate':forms.Select(choices=VAT_RATE,attrs={'style':'width:100%','style':'height:100%'}),
            'brutto_price_per_package':forms.NumberInput(attrs={'style':'width:100%'})
        }

        labels = {
            'category':'Kategoria',
            'subcategory':'Podkategoria',
            'aisle':'Segment',
            'name':'Produkt',
            'unit':'Jednostka',
            'grammature_per_package':'Ilość',
            'vat_rate':'Stawka VAT',
            'brutto_price_per_package':'Cena brutto'
         }

BistroManagementToolApp/views.py
from BistroManagementToolApp.models import *
from BistroManagementToolApp.forms import *

from datetime import date
from django.shortcuts import render
from django.shortcuts import redirect

from django.http.response import JsonResponse
from django.http.response import HttpResponse
from django.http.response import HttpResponseRedirect

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth import authenticate,login,logout

from django.forms import formset_factory

# Widoki powiązane z poszczególnymi template'ami

# Widok odpowiedzalny za obsługę panelu administratora

@login_required
@user_passes_test(lambda u: u.groups.filter(name='Owner').exists(),login_url='/bistro/brak_uprawnien')
def panel_administratora(request):
    my_dict = {}
    return render(request, 'BistroManagementToolApp/panel_administratora.html',context=my_dict)

# Widok odpowiedzialny za obsługę panelu rejestracji

@login_required
def panel_zarzadzania_zespolem(request):

    forms = [UserForm(),ApplicationUserForm()]
    application_users = ApplicationUser.objects.order_by('-user__date_joined').all()
    my_dict = {'forms':forms,'application_users':application_users}

    return render(request, 'BistroManagementToolApp/panel_zarzadzania_zespolem.html', context=my_dict)

# Widok odpowiedzielany za wylogowanie urzytkownika

@login_required
def logout_user(request):
    logout(request)
    return redirect('/bistro/panel_logowania')

# Strona wyświetlana użytkownikom, którzy nie mają upranień do odwiedzenia
# danej strony

@login_required
def brak_uprawnien(request):
    return render(request, 'BistroManagementToolApp/brak_uprawnien.html')

# Strona wyświetlana użytkownikom, którzy nie są zalogowani

def login_required_page(request):
    return render(request, 'BistroManagementToolApp/login_required_page.html')

# Strona wyświetlana użytkownikom, którzy podali błędne dane logowania

def wrong_credentials_page(request):
    return render(request, 'BistroManagementToolApp/wrong_credentials_page.html')

# Widok odpowiedzialny za obsługę panelu logowania

def panel_logowania(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                if User.objects.get(username=username).groups.filter(name='Employee').exists():
                    return redirect('/bistro/panel_sprzedawcy')
                else:
                    return redirect('/bistro/panel_administratora')
            else:
                return HttpResponse('Account not active')
        else:
            return redirect('/bistro/wrong_credentials_page')
    else:
        application_users = ApplicationUser.objects.all()
        my_dict = {'application_users':application_users}
        return render(request, 'BistroManagementToolApp/panel_logowania.html', context=my_dict)

# Widok odpowiedzialny za    obsługę panelu sprzedawcy

@login_required
def panel_sprzedawcy(request):

    my_dict = {}
    return render(request, 'BistroManagementToolApp/panel_sprzedawcy.html', context=my_dict)

# Widok opowiedzialny za obłsuge panelu transakcji

@login_required
def panel_transakcji(request):

    # Tworzymy zespół formularzy do umieszczenia na stronie

    ProductsInTransactionFormset = formset_factory(ProductsInTransactionForm)

    if request.method == 'POST':
        products_in_transaction_formset = ProductsInTransactionFormset(request.POST)
        if products_in_transaction_formset.is_valid():
            if len(products_in_transaction_formset.forms) > 1:
                new_transaction = TransactionForm().save(commit=False)
                new_transaction.date_created = datetime.now()
                new_transaction.sales_person = ApplicationUser.objects.get(user=request.user)
                for f in products_in_transaction_formset[1:]:
                    new_transaction.number_of_products_in_transaction += float(f.cleaned_data['quantity'])
                    new_transaction.netto_transaction_value += float(Product.objects.get(name=f.cleaned_data['product']).netto_price * f.cleaned_data['quantity'])
                    new_transaction.vat_due_in_transaction += float(Product.objects.get(name=f.cleaned_data['product']).vat_paid * f.cleaned_data['quantity'])
                    new_transaction.brutto_transaction_value += float(Product.objects.get(name=f.cleaned_data['product']).brutto_price * f.cleaned_data['quantity'])
                new_transaction.save()
                for f in products_in_transaction_formset[1:]:
                    f = f.save(commit=False)
                    f.transaction = new_transaction
                    f.save()

            products_in_transaction_formset = ProductsInTransactionFormset()
            transactions = Transaction.objects.order_by('-date_created').all()
            product_groups = ProductGroup.objects.all()
            product_items = Product.objects.all()
            my_dict = {'transactions': transactions, 'product_groups': product_groups, 'product_items': product_items,
                       'form_set': products_in_transaction_formset}
            return render(request, 'BistroManagementToolApp/panel_transakcji.html', context=my_dict)

        else:
            print(products_in_transaction_formset.errors)
            return render(request, 'BistroManagementToolApp/panel_sprzedawcy.html')
    else:
            # Tworzymy instancje zestawu formularzy,którą wstrzykniemy na strone
            # poprzez słownik

        products_in_transaction_formset = ProductsInTransactionFormset()
        transactions = Transaction.objects.order_by('-date_created').all()
        product_groups = ProductGroup.objects.all()
        product_items = Product.objects.all()
        my_dict = {'transactions':transactions,'product_groups':product_groups,'product_items':product_items,'form_set':products_in_transaction_formset}
        return render(request, 'BistroManagementToolApp/panel_transakcji.html', context=my_dict)

# Widok odpowiedzialny za obsługę panelu magazynu

@login_required
def panel_magazynu(request):

        ingredients = Ingredient.objects.order_by('-date_created').all()
        ingredient_form = IngredientForm()
        my_dict = {'ingredients': ingredients, 'ingredient_form': ingredient_form}
        return render(request, 'BistroManagementToolApp/panel_magazynu.html', context=my_dict)

# Widoki obsługujące zapytania AJAX-owe

# Utworzenie nowego pracownika

@login_required
def create_user(request):

    if request.method == "POST":
        user_form = UserForm(request.POST)
        user_application_form = ApplicationUserForm(request.POST)

        if user_form.is_valid() and user_application_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            application_user = user_application_form.save(commit=False)
            application_user.user = user
            if 'picture' in request.FILES:
                application_user.picture = request.FILES['picture']

            application_user.save()

            return redirect('/bistro/panel_zarzadzania_zespolem')

        else:
            forms = [user_form, user_application_form]
            application_users = ApplicationUser.objects.order_by('-user__date_joined').all()
            my_dict = {'show_add_user_window': True, 'forms': forms, 'application_users': application_users}
            return render(request, 'BistroManagementToolApp/panel_zarzadzania_zespolem.html', context=my_dict)

# Skasuj istniejącego pracownika

@login_required
def delete_user(request):

    ApplicationUser.objects.get(user = User.objects.get(id=request.GET.get('user_id'))).delete()
    User.objects.get(id=request.GET.get('user_id')).delete()

    data = {
        'status':'User deleted!'
    }
    return JsonResponse(data)


# Wyedytuj wskazanego pracownika

@login_required
def edit_user(request):
   return JsonResponse({'Status':'Ok'})

# Utworzenie nowego składnika

@login_required
def create_ingredient(request):
    if request.method == "POST":
        ingredient_form = IngredientForm(request.POST)
    else:
        ingredient_form = IngredientForm()

    return save_ingredient(request,ingredient_form)

# Update istniejącego składnika

@login_required
def update_ingredient(request):
    ingredient_form = Ingredient.objects.get(ext_id=request.GET.get('ingredient_ext_id'))
    if request.method == "POST":
        ingredient_form = IngredientForm(request.POST,instance=ingredient_form)
    else:
        ingredient_form = IngredientForm(instance=ingredient_form)

    return save_ingredient(request,ingredient_form)

# Zapisz nowy składnik

@login_required
def save_ingredient(request,ingredient_form):

    if ingredient_form.is_valid():
            new_ingredient = ingredient_form.save(commit=False)
            new_ingredient.ext_id = "S"+str(len(Ingredient.objects.all())+1)
            new_ingredient.date_created = date.today()
            new_ingredient.status = True
            new_ingredient.brutto_price_per_unit = ingredient_form.cleaned_data['brutto_price_per_package'] / ingredient_form.cleaned_data['grammature_per_package']
            new_ingredient.amount_in_storage = 0
            new_ingredient.netto_price_per_package = ingredient_form.cleaned_data['brutto_price_per_package'] / (1 + (ingredient_form.cleaned_data['vat_rate']))
            new_ingredient.netto_price_per_unit = new_ingredient.netto_price_per_package / ingredient_form.cleaned_data['grammature_per_package']
            new_ingredient.save()

            ingredient_form = IngredientForm()
            ingredients = Ingredient.objects.order_by('-date_created').all()

templates/BistroManagementToolApp/brak_uprawnien.html
<!DOCTYPE html>

{% extends "BistroManagementToolApp/base.html" %}

{% load static %}

{% block own_css_block %}
    <link rel="stylesheet" href={% static "css/BistroManagementToolApp/styles_main.css" %}>
{% endblock %}

{% block title %}
    Brak uprawnień
{% endblock %}

{% block body_block %}
    <div style="display: flex;flex-direction: column;text-align: center;padding: 5px;margin-top: 50px">
        <h3>Nie masz uprawnień, żeby otworzyć tą stronę!</h3>
        <a href="{% url 'BistroManagementToolApp:panel_sprzedawcy' %}">Wróć do panelu sprzedawcy</a>
    </div>
{% endblock %}

{% block optional_javascript_block %}
{% endblock %}

{% block own_javascript_block %}
    <script src="../../static/js/BistroManagementToolApp/panel_logowania_scripts.js"></script>
{% endblock %}

templates/BistroManagementToolApp/panel_administratora.html
<!DOCTYPE html>

{% extends "BistroManagementToolApp/base.html" %}

{% load static %}

{% block own_css_block %}

    <link rel="stylesheet" href={% static "css/BistroManagementToolApp/styles_main.css"  %}>
    <link rel="stylesheet" href={% static "css/BistroManagementToolApp/styles_admin_page.css" %}>

{% endblock %}

{% block title %}
    Panel administratora
{% endblock %}

{% block body_block %}

    <div class="admin_actions">
        <button id="menu" class="admin-action"><strong>Zarządzaj menu</strong></button>
        <button id="magazyn" class="admin-action" onclick="location.href='{% url 'BistroManagementToolApp:panel_magazynu' %}'" ><strong>Zarządzaj magazynem</strong></button>
        <button id="zamowienia" class="admin-action"><strong>Status zamowień</strong></button>
        <button id="koszty" class="admin-action"><strong>Zarządzaj kosztami</strong></button>
        <button id="personel" class="admin-action" onclick="location.href='{% url 'BistroManagementToolApp:panel_zarzadzania_zespolem' %}'"><strong>Zarządzaj personelem</strong></button>
        <button id="analityka" class="admin-action"><strong>Analityka i raporty</strong></button>
        <button id="kamery" class="admin-action" onclick ="location.href='{% url 'BistroManagementToolApp:panel_sprzedawcy' %}'"><strong>Panel sprzedawcy</strong></button>
        <button id="koniec_pracy" class="admin-action" onclick ="location.href='{% url 'BistroManagementToolApp:logout_user' %}'"><strong>Zakończ pracę</strong></button>
    </div>

{% endblock %}

{% block optional_javascript_block %}
{% endblock %}

{% block own_javascript_block %}
{% endblock %}

templates/BistroManagementToolApp/panel_magazynu.html
<!DOCTYPE html>

<!-- TODO do każdego diva będącego ingredientem dodać ikonkę usuń i edytuj wraz z towarzyszącymi funkcjonalnościami -->
<!-- TODO w panelu zarządania magazynem dodać funkcje umożliwją dodawanie nowych kategorii,podkategorii, segmentów -->
<!-- TODO w panelu zarządania magazynem dodać funkcjonalność dodawania zakupów -->
<!-- TODO do przycisku Zarządzaj menu dodać link przenoszący do Strony zarządzaj menu -->
<!-- TODO dodać pytanie czy na pewno chcesz usunąć składnik-->

{% extends "BistroManagementToolApp/base.html" %}

{% load static %}

{% block own_css_block %}
    <link rel="stylesheet" href={% static "css/BistroManagementToolApp/styles_main.css" %}>
    <link rel="stylesheet" href={% static "css/BistroManagementToolApp/styles_wharehouse_page.css" %}>
{% endblock %}

{% block title %}
    Magazyn składników
{% endblock %}

{% block body_block %}
    <div id="ingredient_window" class="users_window_form_hidden">
        <div class="users_window_header">
            <div id="head_buttons" class="usr_buttons_form_hidden header_item"></div>
            <div id="head_category" class="usr_image_form_hidden header_item">Kategoria</div>
            <div id="head_subcategory" class="usr_username_form_hidden header_item">Podkategoria</div>
            <div id="head_aisle" class="usr_firstname_form_hidden header_item">Segment</div>
            <div id="head_name" class="usr_lastname_form_hidden header_item">Nazwa</div>
            <div id="head_unit" class="usr_email_form_hidden header_item">Jedn.</div>
            <div id="head_gramature" class="usr_status_form_hidden header_item">Ilość</div>
            <div id="head_netto" class="usr_lastlogin_form_hidden header_item">Cena netto</div>
            <div id="head_vat" class="usr_datecreated_form_hidden header_item">VAT</div>
            <div id="head_brutto" class="usr_salary_form_hidden header_item">Cena brutto</div>
            <div id="head_amount" class="usr_tenure_form_hidden header_item">Zapas</div>
        </div>
         <div class="users_window_main disable-scrollbars">
             {% for ing in ingredients %}
             <div id="ingredient_{{ ing.ext_id }}" class="user_window_item">
                <div id="ing_buttons_{{ ing.ext_id }}" class="usr_buttons_form_hidden" style="display: flex; flex-direction: column;height: 100%; justify-content: center;align-items: center;padding: 3px;row-gap: 2px">
                    <button id='edit_ingredient_{{ ing.ext_id }}' data-ingredient_ext_id='{{ ing.ext_id }}' style='color:black;width: 90%;height: 48%;'><i class='fas fa-edit'></i></button>
                    <button id='remove_ingredient_{{ ing.ext_id }}' data-ingredient_ext_id='{{ ing.ext_id }}' style='color:black;width: 90%;height: 48%;'><i class='fas fa-trash-alt'></i></button>
                </div>
                <div id='ing_category_{{ ing.ext_id }}' class="usr_image_form_hidden user_item">{{ing.category}}</div>
                <div id='ing_subcategory_{{ ing.ext_id }}' class="usr_username_form_hidden user_item">{{ing.subcategory}}</div>
                <div id='ing_aisle_{{ ing.ext_id }}' class="usr_firstname_form_hidden user_item">{{ ing.aisle }}</div>
                <div id='ing_name_{{ ing.ext_id }}' class="usr_lastname_form_hidden user_item">{{ing.name}}</div>
                <div id='ing_unit_{{ ing.ext_id }}' class="usr_email_form_hidden user_item">{{ing.unit}}</div>
                <div id='ing_gramature_{{ ing.ext_id }}' class="usr_status_form_hidden user_item">{{ ing.grammature_per_package }}</div>
                <div id='ing_netto_{{ ing.ext_id }}' class="usr_lastlogin_form_hidden user_item">{{ing.netto_price_per_package}}</div>
                <div id='ing_vat_{{ ing.ext_id }}' class="usr_datecreated_form_hidden user_item">{{ing.vat_rate}}</div>
                <div id='ing_brutto_{{ ing.ext_id }}' class="usr_salary_form_hidden user_item">{{ing.brutto_price_per_package}}</div>
                <div id='ing_amount_{{ ing.ext_id }}' class="usr_tenure_form_hidden user_item">{{ing.amount_in_storage}}</div>
             </div>
             {% endfor %}
        </div>
    </div>
    <div id="ingredient_form_1" class="user_form_hidden">
        <div class="user_form_header">
            Utwórz składnik
        </div>
        <div class="user_form_main">
            <form method="POST" action="{% url 'BistroManagementToolApp:create_ingredient' %}">
                <div id="form_fields_area" class="form_fields_area_errors_hidden">
                    <div class="form_fields_line">
                        <div id="ingredient_category" class="form_field" style="width:100%">
                            {{ ingredient_form.category.label_tag }}
                            {{ ingredient_form.category}}
                        </div>
                    </div>
                    <div class="form_fields_line">
                        <div id="ingredient_subcategory" class="form_field" style="width:100%">
                            {{ ingredient_form.subcategory.label_tag }}
                            {{ ingredient_form.subcategory }}
                        </div>
                    </div>
                    <div class="form_fields_line">
                        <div id="ingredient_aisle" class="form_field" style="width:100%">
                            {{ ingredient_form.aisle.label_tag }}
                            {{ ingredient_form.aisle}}
                        </div>
                    </div>
                     <div class="form_fields_line">
                        <div class="form_field" style="width:100%">
                        {{ ingredient_form.name.label_tag }}
                        {{ ingredient_form.name }}
                        </div>
                     </div>
                     <div class="form_fields_line">
                        <div class="form_field" style="width:25%">
                            {{ ingredient_form.unit.label_tag }}
                            {{ ingredient_form.unit }}
                        </div>
                        <div class="form_field" style="width:25%">
                            {{ ingredient_form.grammature_per_package.label_tag }}
                            {{ ingredient_form.grammature_per_package}}
                        </div>
                        <div class="form_field" style="width:25%">
                            {{ ingredient_form.brutto_price_per_package.label_tag }}
                            {{ ingredient_form.brutto_price_per_package}}
                        </div>
                        <div class="form_field" style="width:25%">
                            {{ ingredient_form.vat_rate.label_tag }}
                            {{ ingredient_form.vat_rate}}
                        </div>
                     </div>
                </div>
                 <div id="form_error_line" class="form_error_line_hidden">
                       <div class="form_field" style="width: 100%;justify-content: flex-start">
                           <p><strong>Your form has following errors:</strong></p>
                           {% for field in addNewIngredientForm %}
                               {% for error in field.errors %}
                                   <p style="color:red;line-height: 0.5em">{{ field.label_tag}} {{error }}</p>
                               {% endfor %}
                           {% endfor %}
                           {% for error in addNewIngredientForm.non_field_errors %}
                               <p style="color:red">{{ error}}</p>
                           {% endfor %}
                       </div>
                 </div>
               {% csrf_token %}

               <div class="form_fields_line" style="align-items: flex-end">
                   {% if addNewIngredientForm.errors %}
                       <input id="add_ingredient_show_errors" style="height: 50%;width: 100%" type="button" value="Pokaż błędy!">
                   {% endif %}
                   <input id="add_ingredient_cancel" style="height: 50%" type="button" value="Anuluj">
                   <input id="add_ingredient" type="submit"  style="height: 50%" value="Utwórz">
               </div>
            </form>
        </div>
    </div>
    <div id="ingredient_form_2" class="user_form_hidden">
        <div class="user_form_header">
            Wprowadź zakupy do systemu
        </div>
        <div class="user_form_main">

        </div>
    </div>
    <div class="user_menu_panel">
        <button id="ingredient_menu_b1" class="user_menu_panel_item"><strong>Utwórz składnik</strong></button>
        <button id="ingredient_menu_b2" class="user_menu_panel_item"><strong>Dodaj zakupy</strong></button>
        <button id="ingredient_menu_b3" class="user_menu_panel_item"><strong>Zarządaj menu</strong></button>
        <button id="ingredient_menu_b4" onclick ="location.href='{% url 'BistroManagementToolApp:panel_administratora' %}'" class="user_menu_panel_item"><strong>Powrót</strong></button>
    </div>
{% endblock %}

{% block optional_javascript_block %}
    <script>
        {% if show_add_ingredient_window %}
            var show_add_ingredient_window = true;
        {% else %}
            var show_add_ingredient_window = false;
        {% endif %}
    </script>
{% endblock %}

{% block own_javascript_block %}
    <script src="../../static/js/BistroManagementToolApp/panel_magazynu_scripts.js"></script>
{% endblock %}

templates/BistroManagementToolApp/panel_sprzedawcy.html
<!DOCTYPE html>

<!-- TODO Dodać funkcje wylogowywania sie z sesji -->

{% extends "BistroManagementToolApp/base.html" %}

{% load static %}

{% block own_css_block %}
    <link rel="stylesheet" href={% static "css/BistroManagementToolApp/styles_main.css"  %}>
    <link rel="stylesheet" href={% static "css/BistroManagementToolApp/styles_sales_page.css" %}>
{% endblock %}

{% block title %}
    Panel sprzedawcy
{% endblock %}

{% block body_block %}
    <div class="frontline_actions">
        <button id="szybka_transakcja" class="frontline-action" onclick ="location.href='{% url 'BistroManagementToolApp:panel_transakcji' %}'"><strong>Szybka transakcja</strong></button>
        <button id="otworz_rachunek" class="frontline-action"><strong>Otwórz rachunek</strong></button>
        <button id="zamowienie_na_dowoz" class="frontline-action"><strong>Dowóz</strong></button>
        <button id="rachunki_otwarte" class="frontline-action"><strong>Rachunki otwarte</strong></button>
        <button id="lista_dostaw" class="frontline-action"><strong>Lista dostaw</strong></button>
        <button id="status_zamowien" class="frontline-action"><strong>Status zamówień</strong></button>
        <button id="pokaz_oferte" class="frontline-action"><strong>Pokaż ofertę</strong></button>
        <button id="pokaz_grafik" class="frontline-action"><strong>Pokaż grafik</strong></button>
        <button id="rozpocznij_zmiane" class="frontline-action"><strong>Rozpocznij zmianę</strong></button>
        <button id="raport_finansowy" class="frontline-action"><strong>Raport finansowy</strong></button>
        <button id="rozlicz_sie" class="frontline-action" onclick ="location.href='{% url 'BistroManagementToolApp:panel_administratora' %}'"><strong>Panel właściciela</strong></button>
        <button id="koniec_zmiany" class="frontline-action" onclick ="location.href='{% url 'BistroManagementToolApp:logout_user' %}'"><strong>Zakończ zmianę</strong></button>
    </div>
{% endblock %}

{% block optional_javascript_block %}
{% endblock %}

{% block own_javascript_block %}
{% endblock %}